/*************************************************************************
   This file containts a set a "nohop" routines  as replacments routines 
   for capability that is not supported in this release. 
*************************************************************************/
void dbUpdateInitialParms(){}
void dataBroker_init(){}
void RunAllUnitTests(){}
void shutdownDB(){}
void connectToDB(){}
void postTotalEnergies(){}
void updateDataBrokerContent(){}
void slave_dumpprofile(){}
void mgptgetNgraphs(){}
void buf1cap(){}
void buf2cap(){}
void nresizings(){}
void eam_opt_has_run(){}
void mgptTempStorageSize(){}
void voronoiLoadBalance_init(){}
void voronoiLoadBalanceWrite(){}
void voronoiLoadBalanceFunction(){}
void kn(){}
void relativistic_parms(){}
void relativisticLangevin_parms(){}
void TNBurn_parms(){}
void radiation_parms(){}
void localYukawaParse(){}
void hycopLangevinParse(){}
void skupskyParse(){}
void pnglf_parms(){}
void hycopIntegrator_parms(){}
void pnglf(){}
void hycopIntegrator(){}
void cdb_parms(){}
void event_parms(){}
void ewaldAnalysis_parms(){}
void localYukawaAnalysis_parms(){}
void npartHist_parms(){}
void projectileRV_parms(){}
void ewaldTransportCoeff_parms(){}
void nearMiss_parms(){}
void boundState_parms(){}
void vonMises_parms(){}
void plasmaWake_parms(){}
void cdb_output(){}
void cdb_eval(){}
void event_output(){}
void event_eval(){}
void ewaldAnalysis_output(){}
void ewaldAnalysis_eval(){}
void localYukawaAnalysis_output(){}
void localYukawaAnalysis_eval(){}
void npartHist_clear(){}
void npartHist_output(){}
void npartHist_eval(){}
void projectileRV_clear(){}
void projectileRV_output(){}
void projectileRV_eval(){}
void ewaldTransportCoeff_output(){}
void ewaldTransportCoeff_eval(){}
void nearMiss_output(){}
void nearMiss_eval(){}
void boundState_output(){}
void boundState_eval(){}
void vonMises_output(){}
void vonMises_eval(){}
void plasmaWake_clear(){}
void plasmaWake_output(){}
void plasmaWake_eval(){}
void meam_parms(){}
void fmm_parms(){}
void plasmaInit(){}
void ewald_parms(){}
void hycopInit(){}
void localYukawaInit(){}
void eam_onepass_parms(){}
void eam_opt_parms(){}
void eam2pass_parms(){}
void eam1pass_parms(){}
void onebody_parms(){}
void mgpt_parms(){}
void meam(){}
void meamCutoff(){}
void fmmCompute_ddcMD(){}
void fmmCutoff(){}
void plasma_write_dynamic(){}
void plasmaCutoff(){}
void ewald(){}
void ewaldCutoff(){}
void hycop(){}
void hycopCutoff(){}
void localYukawa(){}
void localYukawaCutoff(){}
void eam_onepass(){}
void eam_onepassCutoff(){}
void eam_opt(){}
void eam_optCutoff(){}
void eam2pass(){}
void eam2passCutoff(){}
void eam1pass(){}
void eam1passCutoff(){}
void onebody(){}
void onebodyCutoff(){}
void mgpt(){}
void mgptCutoff(){}
void opt_transform(){}
void opt_box(){}
void find_strips(){}
